apiVersion: v1
kind: Pod
metadata:
  name: test-projected-volume
spec:
  containers:
  - name: test-secret-volume
    image: busybox
    args:
      - sleep
      - "86400"
    volumeMounts:
      - mountPath: "/projected-volume"
        name: mysql-cred
        readOnly: true
    resources:
      limits:
        memory: "50Mi"
        cpu: "100m"
  # volumes:
  #   - name: mysql-cred
  #     projected:
  #       sources:
  #         - secret:
  #             name: user
  #         - secret:
  #             name: pass
  volumes:
    - name: mysql-cred
      projected:
        sources:
          - secret:
              name: mysecret
# 无法使用kubectl apply -f 更新

