apiVersion: v1
kind: Pod
metadata:
  name: liveness
  labels:
    test: liveness
spec:
  containers:
  - name: liveness
    image: busybox
    command: ["/bin/sh"]
    args:
      - "-c"
      - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 60
    livenessProbe:
      exec:
        command:
          - cat
          - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
    imagePullPolicy: Always
    resources:
      limits:
        memory: "50Mi"
        cpu: "100m"
